version: '3.8'
services:
  api:
    build: .
    command: uvicorn main:create_app --factory --host 0.0.0.0 --port 8000
    volumes:
      - ./logs:/app/logs
      - ./static:/app/static
      - ./docs:/app/docs
      - ./.env.prod:/app/.env
    env_file:
      - .env.prod
    expose:
      - "8000"
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html/static:ro
      - ./certs:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api 