openai:
  api_key: ${OPENAI_API_KEY}
  model: gpt-3.5-turbo-1106
  temperature: 0
  max_tokens: 128

google:
  api_key: ${GOOGLE_API_KEY}
  places_endpoint: https://maps.googleapis.com/maps/api/place/nearbysearch/json

redis:
  uri: ${REDIS_URI}
  db: 0

playwright:
  browsers: [chromium, firefox, webkit]
  headless: true
  concurrency: 3
  timeout: 45 