level: INFO
log_to_file: true
file_path: logs/app.log
max_bytes: 1048576
backup_count: 5
error_file_path: logs/error.log
env: dev
# All logs include trace_id for correlation
# Example log entry:
# {"event": "unhandled_exception", "error": {"type": "InvalidGoalError", ...}, "trace_id": "123e4567-e89b-12d3-a456-426614174000", ...} 